from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TestConfig:
    test_num: int
    title: str
    dimension: int
    n_value: int
    modifier: int | None
    p_values: tuple[int, ...]
    parse_kind: str
    chart_coords: tuple[int, ...]


TEST_CATALOG: dict[int, TestConfig] = {
    22: TestConfig(
        test_num=22,
        title="DNA",
        dimension=31,
        n_value=2097161,
        modifier=None,
        p_values=(3, 4, 5, 6, 7),
        parse_kind="vector_anyfloat",
        chart_coords=(0, 30),
    ),
    23: TestConfig(
        test_num=23,
        title="Count the 1s in a Stream of Bytes",
        dimension=1,
        n_value=0,
        modifier=None,
        p_values=(100, 150, 200, 250, 300),
        parse_kind="single_anyfloat",
        chart_coords=(0,),
    ),
    24: TestConfig(
        test_num=24,
        title="Count the 1s for Specific Bytes",
        dimension=4,
        n_value=0,
        modifier=None,
        p_values=(10, 20, 30, 40, 50),
        parse_kind="vector_lastline",
        chart_coords=(0, 3),
    ),
    25: TestConfig(
        test_num=25,
        title="Parking",
        dimension=1,
        n_value=24000,
        modifier=None,
        p_values=(10, 20, 30, 40, 50),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    26: TestConfig(
        test_num=26,
        title="Squeeze",
        dimension=1,
        n_value=0,
        modifier=None,
        p_values=(2, 3, 4, 5, 6),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    27: TestConfig(
        test_num=27,
        title="OPERM5",
        dimension=1,
        n_value=1000000,
        modifier=None,
        p_values=(5, 10, 15, 20, 24),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    28: TestConfig(
        test_num=28,
        title="Craps",
        dimension=2,
        n_value=0,
        modifier=None,
        p_values=(5, 10, 15, 20, 25),
        parse_kind="vector_lastline",
        chart_coords=(0, 1),
    ),
    29: TestConfig(
        test_num=29,
        title="DAB DCT",
        dimension=1,
        n_value=4096,
        modifier=None,
        p_values=(5, 10, 20, 30, 40, 50),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    30: TestConfig(
        test_num=30,
        title="DAB Filtering",
        dimension=1,
        n_value=4096,
        modifier=None,
        p_values=(5, 10, 20, 30, 40, 50),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    31: TestConfig(
        test_num=31,
        title="Linear Complexity",
        dimension=1,
        n_value=4096,
        modifier=500,
        p_values=(5, 10, 20, 30, 40, 50),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    32: TestConfig(
        test_num=32,
        title="NIST Random Excursions",
        dimension=8,
        n_value=1000000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="vector_anyfloat",
        chart_coords=(0, 7),
    ),
    33: TestConfig(
        test_num=33,
        title="NIST Random Excursions Variant",
        dimension=18,
        n_value=1000000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="vector_anyfloat",
        chart_coords=(0, 17),
    ),
    34: TestConfig(
        test_num=34,
        title="Diehard 3D Spheres",
        dimension=1,
        n_value=12000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    35: TestConfig(
        test_num=35,
        title="Marsaglia-Tsang GCD",
        dimension=1,
        n_value=50000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    36: TestConfig(
        test_num=36,
        title="NIST Nonperiodic Template Matching",
        dimension=148,
        n_value=2000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="vector_anyfloat",
        chart_coords=(0, 147),
    ),
    37: TestConfig(
        test_num=37,
        title="NIST Runs Test",
        dimension=1,
        n_value=100000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    38: TestConfig(
        test_num=38,
        title="NIST Longest Run of Ones",
        dimension=1,
        n_value=100000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    39: TestConfig(
        test_num=39,
        title="NIST Cumulative Sums",
        dimension=2,
        n_value=100000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="vector_lastline",
        chart_coords=(0, 1),
    ),
    40: TestConfig(
        test_num=40,
        title="NIST Approximate Entropy",
        dimension=1,
        n_value=100000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
    41: TestConfig(
        test_num=41,
        title="Maurer Universal Statistical",
        dimension=1,
        n_value=100000,
        modifier=None,
        p_values=(5, 10, 20, 40, 80),
        parse_kind="single_lastline",
        chart_coords=(0,),
    ),
}

